# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [3]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])#, dtype=np.float128)

In [4]:
a

array(['1', '2', '汉'], dtype='<U1')

In [5]:
b

array([1, 2, 3], dtype=uint16)

In [6]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
print(c.shape)

(2, 3)


In [8]:
print(c.dtype)

float64


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [9]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [11]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [12]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-10,   4,   9,   1,  -9],
       [  8,   4,   1,   0,  -7]])

## Индексирование и слайсы

In [14]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[22 67 91 46 22 35 69 71 19 98]
 [82 83 14 34 16 76 20 99 45  9]
 [85 35 73 41 20 16 14 37 58 38]
 [86  0 25 83 71 36 10 68 20 21]
 [22 37 15 97 60 21  8 76 74 48]]


In [15]:
a[0]

array([22, 67, 91, 46, 22, 35, 69, 71, 19, 98])

In [16]:
a[0, 1] # the same as a[0][1]

67

In [17]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([67, 83, 35,  0, 37])

In [18]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([19, 45, 58, 20])

In [19]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([22, 15, 60,  8, 74])

In [20]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([37, 97, 21, 76, 48])

In [21]:
# все четные элементы массива:
a[a > 0]

array([22, 67, 91, 46, 22, 35, 69, 71, 19, 98, 82, 83, 14, 34, 16, 76, 20,
       99, 45,  9, 85, 35, 73, 41, 20, 16, 14, 37, 58, 38, 86, 25, 83, 71,
       36, 10, 68, 20, 21, 22, 37, 15, 97, 60, 21,  8, 76, 74, 48])

In [22]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[22, 67, 91, 46, 22, 35, 69, 71, 19, 98],
       [22, 37, 15, 97, 60, 21,  8, 76, 74, 48]])

### Для присваивания тоже работает!

In [23]:
a

array([[22, 67, 91, 46, 22, 35, 69, 71, 19, 98],
       [82, 83, 14, 34, 16, 76, 20, 99, 45,  9],
       [85, 35, 73, 41, 20, 16, 14, 37, 58, 38],
       [86,  0, 25, 83, 71, 36, 10, 68, 20, 21],
       [22, 37, 15, 97, 60, 21,  8, 76, 74, 48]])

In [24]:
a[1:-1, :] = 1
a

array([[22, 67, 91, 46, 22, 35, 69, 71, 19, 98],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [22, 37, 15, 97, 60, 21,  8, 76, 74, 48]])

In [25]:
a[:, 1:3] = np.arange(2)
a

array([[22,  0,  1, 46, 22, 35, 69, 71, 19, 98],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [22,  0,  1, 97, 60, 21,  8, 76, 74, 48]])

## Операции с `np.array`

In [26]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[85 41 12 72]
 [65 76 22 33]
 [54 68 32 78]]

b: [[99  0 90 28]
 [86 88 27  1]
 [94 35 11 21]]

c: [28 51  4 40]



In [27]:
print(a.reshape((2, 6))) # the same as a.shape = (1, 6)

[[85 41 12 72 65 76]
 [22 33 54 68 32 78]]


In [28]:
print(a.T)

[[85 65 54]
 [41 76 68]
 [12 22 32]
 [72 33 78]]


In [29]:
a + b

array([[184,  41, 102, 100],
       [151, 164,  49,  34],
       [148, 103,  43,  99]])

In [30]:
a - b

array([[-14,  41, -78,  44],
       [-21, -12,  -5,  32],
       [-40,  33,  21,  57]])

In [31]:
# какое это умножение?
a * b

array([[8415,    0, 1080, 2016],
       [5590, 6688,  594,   33],
       [5076, 2380,  352, 1638]])

In [32]:
# а это?
a @ b.T

array([[11511, 11314, 11069],
       [ 9339, 12905,  9705],
       [10410, 11570,  9446]])

In [33]:
a / b

C:\Users\Lera\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.85858586,         inf,  0.13333333,  2.57142857],
       [ 0.75581395,  0.86363636,  0.81481481, 33.        ],
       [ 0.57446809,  1.94285714,  2.90909091,  3.71428571]])

In [34]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]], dtype=int32)

In [35]:
np.sqrt(b)

array([[9.94987437, 0.        , 9.48683298, 5.29150262],
       [9.2736185 , 9.38083152, 5.19615242, 1.        ],
       [9.69535971, 5.91607978, 3.31662479, 4.58257569]])

In [36]:
np.sum(b)

580

In [37]:
np.sum(b, axis=0)

array([279, 123, 128,  50])

In [38]:
np.min(a[0])

4

In [39]:
np.vstack([a, b])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [ ]:
np.hstack([a, b])

### Волшебный `np.vectorize`

In [40]:
pow_2 = lambda x: x ** 2

In [41]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16], dtype=int32)

In [42]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [43]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [ ]:
a + d

In [ ]:
a + c

In [ ]:
b - d

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [ ]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

### Задание: написать решалку линейных уравнений

In [ ]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    return None

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [ ]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    return None

## Few more things:

### `np.random.seed()`

In [ ]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

In [ ]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

### `np.isclose()`

In [ ]:
np.float128(1 / 3) * 3 == 1

In [ ]:
np.isclose(np.float128(1 / 3) * 3, 1)

---

# scipy.sparse

In [44]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [45]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

4000112
56


In [48]:
a_csr

<1x1000000 sparse matrix of type '<class 'numpy.int32'>'
	with 498760 stored elements in Compressed Sparse Row format>

In [46]:
a.mean()

0.49876

#### Или можно вот так вот создать:

In [47]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 2, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  9,  0,  0],
       [10,  0,  0,  0,  0]], dtype=int32)